Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/activity_policy.rb
app/policies/application_policy.rb
app/policies/break_policy.rb
app/policies/day_policy.rb
app/policies/plan_policy.rb
app/policies/transport_policy.rb
app/policies/user_policy.rb
test/policies/activity_policy_test.rb
test/policies/break_policy_test.rb
test/policies/day_policy_test.rb
test/policies/plan_policy_test.rb
test/policies/transport_policy_test.rb
test/policies/user_policy_test.rb

installed pundit and created policy pages

installed pundit, and created policy pages

---

Gemfile
Gemfile.lock
app/controllers/activities_controller.rb
app/controllers/api/v1/activities_controller.rb
app/javascript/packs/application.js
app/services/activities_fetcher_service.rb
app/views/activities/index.html.erb
app/views/api/v1/activities/index.json.jbuilder

Shown output if from the HTML view (i.e. on page load), pressing B1 triggers api for refresh of shown results

html & api fetcher service framework, and test page created

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_fonts.scss
app/javascript/packs/application.js
package.json
yarn.lock

Replaced bootstrap library with material library.
https://daemonite.github.io/material/

material library

---

app/assets/stylesheets/config/_colors.scss
app/views/pages/home.html.erb
config/routes.rb

add own color schema

---

app/controllers/plans_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/gmaps.js
app/javascript/plugins/init_autocomplete.js
app/javascript/plugins/timepicker.js
app/services/travel_matrix.rb
app/views/layouts/application.html.erb
app/views/plans/show.html.erb
package.json
yarn.lock

google maps

---

app/assets/stylesheets/components/_checkbox.scss
app/assets/stylesheets/components/_form.scss
app/controllers/plans_controller.rb
app/javascript/packs/application.js
app/views/plans/edit_categories.html.erb

categories

---

app/controllers/activities_controller.rb
app/controllers/api/v1/activities_controller.rb
app/services/activities_fetcher_service.rb
app/services/apis_fetcher_service.rb
app/services/gplace_fetcher_service.rb
app/services/gplace_text_fetcher_service.rb
db/schema.rb

- fixed issue (that existed on my system at least) where 'open-uri' had to required in one file
- removed unnecessary 'require' statements
- clean old debugging code/comments
- hidden Active Record logging to the console for the activity deletions on page load, and the activity saves upon receiving data from the external apis

fixed ubuntu open uri issue and removed debugging

---

app/services/gplace_text_fetcher_service.rb
db/migrate/20190902103920_add_image_to_activity.rb
db/schema.rb

- image_ref (string) col. migration added.
- the ref is added to activities after they are imported via google api

schema updated, image referecne saved following google api call

---

app/models/category.rb
db/migrate/20190903085731_create_categories.rb
db/schema.rb
db/seeds.rb
test/models/category_test.rb

- category model added with attrs
1. name
2. search_term
3 avg_visit_mins
Seed file created with 9 categories

added category model, migration  and seeds

---

app/controllers/api/v1/activities_controller.rb
app/javascript/packs/activities.js
app/policies/activity_policy.rb
app/services/activities_fetcher_service.rb
app/services/apis_fetcher_service.rb
app/services/gplace_details_service.rb
app/services/gplace_fetcher_service.rb
app/services/gplace_text_fetcher_service.rb
app/views/activities/_activity_details.html.erb
app/views/activities/index.html.erb
config/routes.rb

- clicking cards anywhere except the shortlist button creates a modal (popup) containing details of activity/place
- click calls app api (which in turn calls Google Places Details). GPD json is passed to partial view, rendered to string, and passed back to the front end (along with the GPD json itself)
- front end inserts modal html into #modal-container and calsl the modal

Activity details

---

app/controllers/api/v1/activities_controller.rb

added sort by rating

---

app/assets/stylesheets/pages/_index.scss
app/javascript/packs/activities.js
app/views/activities/_shortlisted_activity_card.html.erb
app/views/activities/index.html.erb
db/schema.rb
db/seeds.rb

- switched activities page from grid to flex => fixed issues on chrome
- moved 'continue to itinerary button below shortlist
- added search bar and associated js handling

Search bar

---

app/assets/stylesheets/components/_details-modal.scss
app/assets/stylesheets/components/_index.scss
app/views/activities/_activity_cards.html.erb
app/views/activities/_activity_details.html.erb

modal styled

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_checkbox.scss
app/helpers/plans_helper.rb
app/views/pages/home.html.erb
app/views/plans/edit_categories.html.erb

categories page design V1

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_mini-card.scss
app/assets/stylesheets/pages/_index.scss
app/javascript/packs/activities.js
app/views/activities/_shortlisted_activity_card.html.erb
app/views/activities/index.html.erb

- cards added to shortlist with images
- weired spacing fixed
- icon to search
- next step buttin only appears once 1 activity on shortlist
- better headers

Real shortlist

---

Gemfile
app/controllers/api/v1/activities_controller.rb
app/javascript/packs/activities.js
app/models/plan.rb
app/services/apis_fetcher_service.rb
app/services/gplace_fetcher_service.rb
app/services/gplace_find_place_service.rb
app/services/gplace_text_fetcher_service.rb
config/initializers/geocoder.rb
db/migrate/20190905084528_add_coordinates_to_plans.rb
db/schema.rb

- site functions for any location selected on initial page
- better search:
1) city name appended to search
2) location bias set to coords of plan city

Tweaks 190905

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_how-it-works.scss
app/assets/stylesheets/components/_mini-card.scss
app/javascript/packs/activities.js
app/views/activities/_activity_details.html.erb
app/views/activities/index.html.erb

designed shortlist (fixed box, button, shortlist card design, header for all activities)

activities shortlist

---

app/assets/stylesheets/pages/_index.scss
app/controllers/api/v1/activities_controller.rb
app/javascript/packs/activities.js
app/views/activities/_activity_details.html.erb

- Entering a non-existent place into search displaying error message in input value before fading out, fading back in in reset form.

No info on place

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_checkbox.scss
app/assets/stylesheets/components/_css-grid.scss
app/assets/stylesheets/components/_details-modal.scss
app/assets/stylesheets/components/_form.scss
app/javascript/packs/activities.js
app/views/activities/_activity_details.html.erb
app/views/pages/home.html.erb
app/views/plans/_break_fields.html.erb
app/views/plans/edit.html.erb
app/views/plans/edit_categories.html.erb

modal and pitch feedback fix

---

app/javascript/packs/activities.js
app/services/gplace_details_service.rb
app/services/gplace_fetcher_service.rb
app/services/gplace_find_place_service.rb
app/services/gplace_text_fetcher_service.rb
app/views/activities/_activity_cards.html.erb
app/views/activities/_activity_details.html.erb
app/views/plans/show.html.erb

- added new key references to separate frontend and backend (each environment localhost/staging/production has it's own frontend version, with http referrer restrictions on staging and production
- little tweak. toom char limit on cards down to 40 as was running on 3 line still for some results in HD resolution.

new keys added and references updated
